"""Core configuration constants and defaults for AutoClicker."""

IMAGE_EXTENSIONS = (".png", ".jpg", ".jpeg")
VALID_TEMPLATE_ACTIONS = {"click", "double_click", "click_click", "double", "back"}
VALID_DELAY_TYPES = {"pre", "post"}
VALID_NO_MATCH_ACTIONS = {
    "none",
    "fallback_list",
    "random_click",
    "custom_click",
    "custom_double_click",
    "double_click",
    "click_click",
    "back",
}
CONFIG_FILENAME = "config.json"
TEMPLATE_DIR_NAME = "templates"
FALLBACK_TEMPLATE_DIR_NAME = "fallback_templates"
COUNT_FLUSH_INTERVAL = 5.0
TEMPLATE_MANIFEST_REFRESH_INTERVAL = 1.0
ADB_COMMAND_TIMEOUT = 10.0
ADB_SERVER_PROBE_TIMEOUT = 0.35
ADB_SERVER_START_ATTEMPTS = 3
ADB_SERVER_RETRY_DELAYS = (0.15, 0.35)
ADB_VERSION_TIMEOUT = 5.0
PRESCALE_FACTOR = 0.5
PRESCALE_MIN_TEMPLATE_DIM = 20
LOCAL_VERIFY_MARGIN = 12
LOCAL_VERIFY_TOP_K = 3
HINT_FULL_SCAN_INTERVAL = 10
PERFORMANCE_SAMPLE_LIMIT = 240
DEFAULT_FORCE_SCAN_INTERVAL = 5.0
DEFAULT_ROI_FULL_SCAN_BUDGET = 2
ROI_PRIORITY_TEMPLATE_COUNT = 3
DEFAULT_MAX_IDLE_INTERVAL = 5.0
DEFAULT_CAPTURE_BACKEND = "auto"
VALID_CAPTURE_BACKENDS = {"auto", "png", "raw"}
DEFAULT_ADB_MODE = "bundled"
DEFAULT_CUSTOM_ADB_PATH = ""
VALID_ADB_MODES = {"bundled", "custom"}

ADB_HOST = "127.0.0.1"
ADB_PORT = 5037
DEVICE_ADDRESS = "127.0.0.1:5555"
DEFAULT_SCAN_INTERVAL = 1
DEFAULT_NO_MATCH_TIMEOUT = 120
DEFAULT_SIMILARITY_THRESHOLD = 0.9
DEFAULT_MATCH_GRAYSCALE = True
DEFAULT_ENABLE_RANDOM_CLICK = False
DEFAULT_RANDOM_CLICK_INTERVAL = 30
DEFAULT_DOUBLE_CLICK_INTERVAL = 1.0
DEFAULT_POST_ACTION_DELAY = 2.0
DEFAULT_CONSECUTIVE_MATCH_THRESHOLD = 0
DEFAULT_RESET_COUNTS_ON_STARTUP = False
